name: Sample Workflow

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  draft:
    runs-on: ubuntu-latest

    steps:
      - uses: tauri-apps/tauri-action@v0

      - name: create draft release
        uses: crabnebula-dev/cloud-release
        id: draft
        with:
          command: release draft ${{ secrets.CN_APP_ID }} 0.1.0
          api-key: ${{ secrets.CN_API_KEY }}
